### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by ElSigitas** [augustas2/eldes#13]
**ERROR 1:**

Logger: custom_components.eldes_alarm.core.eldes_cloud
Source: custom_components/eldes_alarm/core/eldes_cloud.py:62
Integration: Eldes Alarm ([documentation](https://github.com/augustas2/eldes/blob/master/README.md), [issues](https://github.com/augustas2/eldes/issues))
First occurred: 18:56:36 (204 occurrences)
Last logged: 21:01:06

Client error on API https://cloud.eldesalarms.com:8083/api/device/info?imei=**************** request 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/info?imei=****************')
Client error on API https://cloud.eldesalarms.com:8083/api/device/list request 403, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/list')

**ERROR 2:**
------------
This error originated from a custom integration.

Logger: custom_components.eldes_alarm
Source: custom_components/eldes_alarm/core/eldes_cloud.py:58
Integration: Eldes Alarm (documentation, issues)
First occurred: 18:56:37 (102 occurrences)
Last logged: 21:01:06

Unknown error occurred during Eldes update request: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/info?imei=*******************')
Unknown error occurred during Eldes update request: 403, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/list')
Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/__init__.py", line 67, in async_update_data
    return await async_get_devices(hass, entry, eldes_client)
  File "/config/custom_components/eldes_alarm/__init__.py", line 105, in async_get_devices
    device["info"] = await eldes_client.get_device_info(device["imei"])
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 128, in get_device_info
    response = await self._api_call(url, "GET")
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 58, in _api_call
    req.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/info?imei=******************')

**Comment by augustas2** [comment]
O kokia signalizacija? Ir kas prie jos prijungta, automatika/temperatūra? Gali tiesiog foto numest iš Eldes app’so.

Ar grybauja kokios kitos integracijos? Meta klaidas, kad negali prisijungti?

Ir koks internetas? Speedtest ką rodo?

**Comment by ElSigitas** [comment]
centralė ESIM384, internetas optika ~100Mbps, pajungta per ELAN3-ALARM modulį + GSM kortelė.

Kitos integracijos veikia. Turiu įtarimą gal, kad Eldes apps'e yra ne vienas objektas, t.y. keletas "location".

home location: visumoje 3 sritys, 4 temperatūros, 6 automatizavimai(4 ON/OFF, 2 pulse), 4 kameros integruotos.

**Comment by ElSigitas** [comment]
![image](https://user-images.githubusercontent.com/6774190/162805912-cbc5bcdb-78b4-4e07-bf10-e7effec6b746.png)
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eldes_alarm/__init__.py:51
Integration: Eldes Alarm (documentation, issues)
First occurred: 21:28:18 (1 occurrences)
Last logged: 21:28:18

Error setting up entry xxxxxxxx@gmail.com for eldes_alarm
Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 52, in _api_call
    req = await self._http_session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/__init__.py", line 49, in async_setup_entry
    await eldes_client.login()
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 78, in login
    resp = await self._api_call(url, "POST", data)
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 52, in _api_call
    req = await self._http_session.request(
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eldes_alarm/__init__.py", line 51, in async_setup_entry
    if ex.status == HTTPStatus.UNAUTHORIZED:
AttributeError: 'TimeoutError' object has no attribute 'status'


--------------------------------------------------------------------------------------------------------------
ir šitas:
This error originated from a custom integration.

Logger: custom_components.eldes_alarm.core.eldes_cloud
Source: custom_components/eldes_alarm/core/eldes_cloud.py:66
Integration: Eldes Alarm (documentation, issues)
First occurred: 21:28:18 (1 occurrences)
Last logged: 21:28:18

Client timeout error on API request https://cloud.eldesalarms.com:8083/api/auth/login

**Comment by augustas2** [comment]
Galimai tada dėl kiekio prietaisų. Nes pas mane beveik nieko nėra, tai per porą savaičių jokios klaidos.

O paskutinę versiją naudoji? Nes pradžioj buvo klaidų integracijoj nemažai. Jei per HACS tada turėtum gaut atnaujinimus.

**Comment by ElSigitas** [comment]
manau, kad paskutinė v1.0.5. Naudoju per HACS.
Turiu pasikūręs 3x HA serverius ant RPI4. Nei viename neveikia :)

![image](https://user-images.githubusercontent.com/6774190/162807820-7d317b78-0dac-44fa-8136-362b590c22a3.png)

**Comment by augustas2** [comment]
Bet bent kartą suveikia? Parodo info apie signalizaciją kažkokią?

**Comment by ElSigitas** [comment]
nei karto, jokios info nematau.

**Comment by augustas2** [comment]
Tai manau viskas kaip ir aišku. Bus galimai "locations" ar sričių problema, kai yra daugiau nei viena. Tiesiog gyvai tokio case pas save neturiu (1 lokacija ir 1 sritis), bet manau pavyks atkartoti ir turėčiau lengvai sutvarkyt.

Informuosiu apie progresą.

**Comment by augustas2** [comment]
Reikėtų dar vieno dalyko, noriu pažiūrėti ką gražina `api/device/list`. Tam kad pamatyt data iš šito request, reiks įjungti `debug` mode ant savo HA serverio.

Pridėk šitas eilutes į `configuration.yml` failą ir perkrauk serverį:
```
logger:
   default: debug
```

Tada nueik į logs, paspausk `Load full Home Assistant log` ir ieškok `get_devices result` ir ten turi būti visos lokacijos tavo. Numesk kodą arba snip'ą. Užtušuok phone, imei ir lokacijos pavadinimą.

Gali atsiųsti tiesiai man ar į email, jei bijai paviešint kažkokius duomenis.

pvz. kaip pas mane tai atrodo:
![image](https://user-images.githubusercontent.com/7789787/162920191-03758def-3b84-47ce-b0a2-18319eaf4ae8.png)

**Comment by simie7** [comment]
Hey, [čia](https://github.com/tanelvakker/eldes-cloud-api) dar vienas repo yra, gal išsitrauksi kažkokios naudingos info.

Aš turiu ELDES dviejose vietose, tai jei ką, galiu padėti su debuginimu. Naudoju rėles, temperatūros daviklius. Kol kas tai pahackinęs, per cron periodiškai išsitraukiu norimas reikšmes, ir per MQTT perduodu HA, tik dabar užtikau šitą repo, tai galim sutelkti pajėgas :) 

O nebandei per modbus pasijungti? Nes mane tai labai domina apeiti cloud'ą ir tiesiai pvz pamatyti atidarytus langus ar stebėti judesio daviklių suveikimą.

**Comment by samuolis** [comment]
> Hey, [čia](https://github.com/tanelvakker/eldes-cloud-api) dar vienas repo yra, gal išsitrauksi kažkokios naudingos info.
> 
> Aš turiu ELDES dviejose vietose, tai jei ką, galiu padėti su debuginimu. Naudoju rėles, temperatūros daviklius. Kol kas tai pahackinęs, per cron periodiškai išsitraukiu norimas reikšmes, ir per MQTT perduodu HA, tik dabar užtikau šitą repo, tai galim sutelkti pajėgas :) 
> 
> O nebandei per modbus pasijungti? Nes mane tai labai domina apeiti cloud'ą ir tiesiai pvz pamatyti atidarytus langus ar stebėti judesio daviklių suveikimą.

Man idomu ar iseitu juos apeiti clouda ju, jei yra tokia galimybe as irgi kiek iseina prisideciau. Patys eldes nelabai nori suteikti jokios informacijos. Kaip supratau jie suteikia informacijos nebent verslo klientams.

Del tos kitos repo, tai as is jos idejau cia tuos logus eldes cloudo. Bet tas repo veikia labai pansiai i sita integracija, tai nezinau ar daug pades.

**Comment by simie7** [comment]
Aš bandžiau tiek tiesiai iš jų, tiek per partnerius, nepavyko.

[Čia](https://github.com/jvitkauskas/EldesReader) dar radau repo, kur tiesiai per USB bando skaityti.

O kalbant apie modbus, tai kažkada šiek tiek bandžiau, nepavyko. Nes visi pulteliai (klaviatūros) būtent per modbus jungiasi, taip pat ir išplėtimo moduliai.

**Comment by samuolis** [comment]
> Aš bandžiau tiek tiesiai iš jų, tiek per partnerius, nepavyko.
> 
> [Čia](https://github.com/jvitkauskas/EldesReader) dar radau repo, kur tiesiai per USB bando skaityti.
> 
> O kalbant apie modbus, tai kažkada šiek tiek bandžiau, nepavyko. Nes visi pulteliai (klaviatūros) būtent per modbus jungiasi, taip pat ir išplėtimo moduliai.

O va sita repo visai idomi. Cia reiktu aisku laiko painvestuoti kad padaryti be cloudo, nes cia jau visiskai custom solutionas gautusi

**Comment by simie7** [comment]
Aš tai įsivaizduoju kažką panašaus į [ESPAltherma](https://raomin.github.io/ESPAltherma/), kur ESP32 prie USB porto prijungus, galima būtų pvz per MQTT gauti visus updeitus. 

Teoriškai kažkaip įsiterpus į komunikaciją tarp [Eldes Utility](https://eldesalarms.com/lt/product/eldes-utility/) ir ESIM, būtų galima išdebuginti ir turėti visą informaciją, tik man biškį žinių šitoj vietoj trūksta.

**Comment by simie7** [comment]
@augustas2 pabandžiau ir aš įsirašyti kaip komponentą ir gavau tokią pačią klaidą, kaip aukščiau paminėta. Įsijungiau debug ir gavau tokį output'ą:
```
2023-02-07 23:30:00.887 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration eldes_alarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-02-07 23:30:07.045 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] login result: {'userRoles': '[ACCOUNT_USER]', 'username': 'myemail@gmail.com', 'token': 'MY-TOKEN'}
2023-02-07 23:30:07.500 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] renew_token result: {'token': 'MY-TOKEN'}
2023-02-07 23:30:07.684 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] get_devices result: [{'imei': 'MY-IMEI-NUMBER', 'name': 'MY-PLACE', 'photoId': 3693, 'migrationPending': False, 'pinCodeProvided': False, 'synchronisationFinished': True, 'partitions': [], 'hasAlarms': False}, {'imei': 'MY-SECOND-IMEI', 'name': 'MY-SECOND-PLACE', 'photoId': 3705, 'migrationPending': False, 'pinCodeProvided': False, 'synchronisationFinished': True, 'partitions': [], 'hasAlarms': False}]
2023-02-07 23:30:08.367 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] get_device_info result: {'imei': 'MY-IMEI-NUMBER', 'status': 'SUCCESS', 'name': 'MY-PLACE', 'model': 'ESIM364', 'firmware': 'V02.15.07', 'phoneNumber': '+MY-PHONE-NR', 'online': True, 'gsmStrength': 1, 'batteryStatus': True, 'migrationPending': False, 'viewCamerasAllowed': False, 'photoId': 3693}
2023-02-07 23:30:08.708 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER request 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER')

2023-02-07 23:30:09.014 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] login result: {'userRoles': '[ACCOUNT_USER]', 'username': 'myemail@gmail.com', 'token': 'MY-TOKEN'}
2023-02-07 23:30:09.747 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] renew_token result: {'token': 'MY_TOKEN'}
2023-02-07 23:30:10.653 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] get_devices result: [{'imei': 'MY-IMEI-NUMBER', 'name': 'MY-PLACE', 'photoId': 3693, 'migrationPending': False, 'pinCodeProvided': False, 'synchronisationFinished': True, 'partitions': [], 'hasAlarms': False}, {'imei': 'MY-SECOND-IMEI', 'name': 'MY-SECOND-PLACE', 'photoId': 3705, 'migrationPending': False, 'pinCodeProvided': False, 'synchronisationFinished': True, 'partitions': [], 'hasAlarms': False}]
2023-02-07 23:30:10.779 DEBUG (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] get_device_info result: {'imei': 'MY-IMEI-NUMBER', 'status': 'SUCCESS', 'name': 'MY-PLACE', 'model': 'ESIM364', 'firmware': 'V02.15.07', 'phoneNumber': '+MY-PHONE-NR', 'online': True, 'gsmStrength': 1, 'batteryStatus': True, 'migrationPending': False, 'viewCamerasAllowed': False, 'photoId': 3693}
2023-02-07 23:30:10.989 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER request 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER')

2023-02-07 23:30:10.991 ERROR (MainThread) [custom_components.eldes_alarm] Unknown error occurred during Eldes update request: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER')
  File "/opt/homeassistant/config/custom_components/eldes_alarm/__init__.py", line 67, in async_update_data
    return await async_get_devices(hass, entry, eldes_client)
  File "/opt/homeassistant/config/custom_components/eldes_alarm/__init__.py", line 106, in async_get_devices
    device["partitions"] = await eldes_client.get_device_partitions(device["imei"])
  File "/opt/homeassistant/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 146, in get_device_partitions
  File "/opt/homeassistant/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 58, in _api_call
aiohttp.client_exceptions.ClientResponseError: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER')
2023-02-07 23:30:10.993 DEBUG (MainThread) [custom_components.eldes_alarm] Finished fetching eldes_alarm data in 3.947 seconds (success: False)
2023-02-07 23:30:10.993 WARNING (MainThread) [homeassistant.config_entries] Config entry 'myemail@gmail.com' for eldes_alarm integration not ready yet: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=MY-IMEI-NUMBER'); Retrying in background
```
Aš pats šiam reikalui naudoju cron, kuris leidžia curl skriptą, output pasitvarkau ir pushinu į mqtt. Turiu įtarimą, kad mano konfigūracija kažkuo skiriasi, nes aš būtinai turiu naudoti ir PIN kodą, kad gaučiau rezultatus. Mano curl atrodo taip (supaprastintai):
```
# Sričių būsenos nuskaitymas
curl -s \
  --header "Accept: application/json, text/plain, */*" \
  --header "Content-Type:application/json" \
  --header "x-whitelable:eldes" \
  --header "Authorization: Bearer $token" \
  -X POST --data '{"pin":"MY-PIN"}' \
  $base/device/partition/list?imei=$imei
```
Pas mane yra dvi signalizacijos, bent vienoje yra kelios sritys, temperatūros, rėlės.

**Comment by samuolis** [comment]
Kaip matau https://www.lrytas.lt/verslas/rinkos-pulsas/2023/04/06/news/bankrutuoja-namu-apsaugos-sistemu-gamintoja-eldes--26660807

Eldes juda link bankroto ir parsiduos kazkam jei pavyks. Tai @simie7 tikriausiai reiktu pasidarbuoti del lokalaus veikimo, netikiu kad ju cloudas kazka ten amazing daro, gal nebent koki security uzmeta ant virsaus

**Comment by simie7** [comment]
Opapa, netikėta. 

Dėl lokalaus tai matau du galimus variantus: 
- yra USB/serial jungtis, kur per ELDES Utility galima konfigūruoti, o Utility mato ir visas būsenas, tai turėtų toks variantas pakankamai pilnavertis būti. Bet šito dar nieko nebandžiau daryti, tik radau (kur nuorodą atmečiau), kad kažkas bandė.
- RS-485/Modbus, nes per šitą magistralę ir klaviatūros pajungtos (galima iki 4 berods jungti), ir išplėtimo moduliai (nepamenu max, bet bent pas mane du moduliai pajungti). Tai tik tiek, kad reikia žinoti magistralė kokiu greičiu dirba, kokiais adresais ką skaityti, žodžiu pasnifinti. Kažkada bandžiau su RS-485-USB adapteriu, bet nieko nepavyko pamatyti, matyt per mažai žinių turiu. O kiek skambinau tiek gamintojui, tiek atstovams (BK Grupė, VS Sistemos), nesuteikė jokios informacijos apie protokolą, tai ties čia ir baigėsi visi bandymai.

**Comment by Barvainis** [comment]
2024-03-16 14:18:36.184 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/auth/login request 401, message='', url=URL('https://cloud.eldesalarms.com:8083/api/auth/login')
2024-03-16 14:18:59.092 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/auth/login request 401, message='', url=URL('https://cloud.eldesalarms.com:8083/api/auth/login')
2024-03-16 14:19:07.174 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/auth/login request 401, message='', url=URL('https://cloud.eldesalarms.com:8083/api/auth/login')
2024-03-16 14:19:12.548 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/auth/login request 401, message='', url=URL('https://cloud.eldesalarms.com:8083/api/auth/login')
2024-03-16 14:20:47.899 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx request 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx')
2024-03-16 14:20:49.060 ERROR (MainThread) [custom_components.eldes_alarm.core.eldes_cloud] Client error on API https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx request 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx')
2024-03-16 14:20:49.062 ERROR (MainThread) [custom_components.eldes_alarm] Unknown error occurred during Eldes update request: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx')
Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/__init__.py", line 69, in async_update_data
    return await async_get_devices(hass, entry, eldes_client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/__init__.py", line 109, in async_get_devices
    device["partitions"] = await eldes_client.get_device_partitions(device["imei"])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 146, in get_device_partitions
    response = await self._api_call(url, "POST", data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 58, in _api_call
    req.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=xxxxxxxx')


Turėjau kelis partition, padariau viena, bet vistiek nepavyksta prisijungti

**Comment by Barvainis** [comment]
Veikia, neveikė todėl kad turėjau  2 objektus

**Comment by rici44** [comment]
hi @augustas2 I have problem to setup eldes alarm hacs integration.  Could you please help me to solve this? I do not know how to process PIN during setup. Thank you. 

I got these errors:

Logger: custom_components.eldes_alarm.core.eldes_cloud
Source: custom_components/eldes_alarm/core/eldes_cloud.py:62
integration: Eldes Alarm ([documentation](https://github.com/augustas2/eldes/blob/master/README.md), [issues](https://github.com/augustas2/eldes/issues))
First occurred: 10:40:36 AM (36 occurrences)
Last logged: 11:25:13 AM

Client error on API https://cloud.eldesalarms.com:8083/api/device/list request 403, message='', url='https://cloud.eldesalarms.com:8083/api/device/list'
Client error on API https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=3xxxxxxxxxxxxxxx7 request 400, message='', url='https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=3xxxxxxxxxxxxxxx7'

Logger: custom_components.eldes_alarm
Source: custom_components/eldes_alarm/__init__.py:69
integration: Eldes Alarm ([documentation](https://github.com/augustas2/eldes/blob/master/README.md), [issues](https://github.com/augustas2/eldes/issues))
First occurred: 10:40:37 AM (18 occurrences)
Last logged: 11:25:13 AM

Unknown error occurred during Eldes update request: 403, message='', url='https://cloud.eldesalarms.com:8083/api/device/list'
Unknown error occurred during Eldes update request: 400, message='', url='https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=3xxxxxxxxxxxxxxx7'
Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/__init__.py", line 69, in async_update_data
    return await async_get_devices(hass, entry, eldes_client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/__init__.py", line 104, in async_get_devices
    devices = await eldes_client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 113, in get_devices
    response = await self._api_call(url, "GET")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 58, in _api_call
    req.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='', url='https://cloud.eldesalarms.com:8083/api/device/list'

**Comment by bernox89** [comment]
do you have any news for this api call error. I have the same error.

**Comment by augustas2** [comment]
Hi, I just started to test a new version with various fixes, including this API error. Expecting to release new version in upcoming week.

**Comment by augustas2** [comment]
The latest update should resolve this issue.
Please update via HACS or manually:
https://github.com/augustas2/eldes/releases/tag/v2.0.0

**Comment by augustas2** [comment]
Inactive. Closing.

> ⚠️ **Deprecation Notice**  
> I am no longer an owner of any Eldes products and will not be maintaining or developing this integration further.  
> If you have development experience and are interested in taking over maintenance of this project, please open an issue or contact me via GitHub.
