### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by vytiskk** [augustas2/eldes#30]
Hi, a few days ago the integration stopped working - any insight on how to troubleshoot?

Žiūriu čia visi lietuviškai rašo :) Iki šiol veikė stabiliai, sistemoje nieko nekeičiau.

This error originated from a custom integration.

Logger: custom_components.eldes_alarm
Source: custom_components/eldes_alarm/__init__.py:69
integration: Eldes Alarm (documentation, issues)
First occurred: 06:49:18 (457 occurrences)
Last logged: 17:02:48

Unknown error occurred during Eldes update request: 403, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/list')
Unknown error occurred during Eldes update request: 400, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/partition/list?imei=357788108511576')
Traceback (most recent call last):
  File "/config/custom_components/eldes_alarm/__init__.py", line 69, in async_update_data
    return await async_get_devices(hass, entry, eldes_client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/__init__.py", line 104, in async_get_devices
    devices = await eldes_client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 113, in get_devices
    response = await self._api_call(url, "GET")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eldes_alarm/core/eldes_cloud.py", line 58, in _api_call
    req.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='', url=URL('https://cloud.eldesalarms.com:8083/api/device/list')

**Comment by augustas2** [comment]
Ar tikrai nustojo veikti? Nes šios klaidos pastoviai kartojasi. Problema žinoma, bet netaisau nes neturiu tiesiog laiko. Problema yra su autentifikacija.
